spring:
  application:
    name: santander-dev-week
  datasource:
    url: jdbc:h2:mem:sdw23
    driverClassName: org.h2.Driver
    username: sdw2023
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true